Solareon patch 4
Qbox-project/qb-ambulancejob pull request #107
Opened 2023-11-28 21:51 UTC by solareon

## Description

Healing a player as ems didn't do anything. This corrects that issue and prevents players from getting stuck in a bed. Items are also now removed when using them. Also adjusted the amounts healed to be more reasonable.

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-11-29 05:24 UTC, Manason requested changes

2023-11-29 05:24 UTC, Manason commented on server/main.lua
> +	TriggerClientEvent('qbx_medical:client:playerRevived', player.PlayerData.source)
This should probably call an server side export? Not sure that this event is intended to be public

2023-11-29 05:24 UTC, Manason commented on server/main.lua
> +	lib.callback("qbx_medical:client:heal", patient.PlayerData.source, false, "full")
This should probably call a server side export.

2023-11-29 05:24 UTC, Manason commented on server/main.lua
> +	local player = exports.qbx_core:GetPlayer(playerId)
player seems to only be used to get playerId anyway, so this could be simplified further not to convert to player.

2023-11-29 05:24 UTC, Manason commented on server/main.lua
>  RegisterNetEvent('hospital:server:RevivePlayer', function(playerId)
Shouldn't we just delete this event altogether in favor of calling qbx_medical exports directly?

2023-11-29 05:24 UTC, Manason commented on client/hospital.lua
> +            TriggerEvent("qbx_medical:client:playerRevived")
Thinking this should be an export. In general I don't think resource A should trigger events owned by resource B. API should be provided via exports.

2023-12-24 14:21 UTC, ChatDisabled commented
@solareon update on requested changes

2023-12-24 14:23 UTC, solareon commented
@ChatDisabled out on Christmas vacation for a couple weeks. I'll work on these when I get back. If someone else would like to work on them I can port them to the main repo and let others hack on it a bit. Just let me know

2024-02-08 07:13 UTC, closed without merging