refactor: spawnVehicle and remove unnecessary functions
Qbox-project/qb-ambulancejob pull request #129
Opened 2024-02-09 02:36 UTC by MafewTM

## Description

- Remove all the unnecessary functions for zones
- Fix the spawning of vehicles to fully utilize the lib module
- Utilization of `qbx.setVehicleExtras`
- Adjust `billPlayer` to pass the source instead of player
- Use `GetVehicleType` to assign plate instead of passing the plate through a bunch of functions

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-02-09 08:05 UTC, solareon requested changes

2024-02-09 08:05 UTC, solareon commented on client/job.lua
> +        end,
```suggestion
        inside = function()
            if QBX.PlayerData.job.type == 'ems' and QBX.PlayerData.job.onduty then
                checkGarageAction(vehicles, coords)
            else
                checkVehicle = false
            end
        end,
        onEnter = function()
            if QBX.PlayerData.job.type == 'ems' and QBX.PlayerData.job.onduty then
                lib.showTextUI(locale('text.veh_button'))
            end
        end,
```

We shouldn't call showTextUI on every tick. 

Additionally depending on how many times we call the EMS check it might be worthwhile to put that into a reusable function for the resource or perhaps an extension to the lib

2024-02-09 08:05 UTC, solareon commented on client/job.lua
>          while checkVehicle do
Can we use `OnKeyPress` here?

2024-02-09 08:05 UTC, solareon commented on client/job.lua
> +                end,
```suggestion
                onEnter = function()
                    local label = QBX.PlayerData.job.onduty and 'text.offduty_button' or 'text.onduty_button'
                    lib.showTextUI(locale(label))
                end,
```
Depending on readability preference this could be stuffed inside the locale call

2024-02-09 08:05 UTC, solareon commented on client/job.lua
> +            end,
```suggestion
            onEnter = function()
                local label = QBX.PlayerData.job.onduty and 'text.elevator_roof' or 'error.not_ems'
                lib.showTextUI(locale(label))
            end,
```
Same thing re: readability

2024-02-09 08:05 UTC, solareon commented on server/hospital.lua
> +    TriggerClientEvent('vehiclekeys:client:SetOwner', source, plate)
```suggestion
	SetVehicleNumberPlateText(veh, plate)
        TriggerClientEvent('vehiclekeys:client:SetOwner', source, plate)
```

2024-02-09 08:05 UTC, solareon commented on client/job.lua
> +            end,
```suggestion
            onEnter = function()
                local label = QBX.PlayerData.job.onduty and 'text.elevator_main' or 'error.not_ems'
                lib.showTextUI(locale(label))
            end,
```
Same re: readability

2024-02-09 08:05 UTC, solareon commented on client/hospital.lua
> +                    end,
```suggestion
                    onEnter = function()
                        local doctorsAvailable = lib.callback.await('qbx_ambulancejob:server:getNumDoctors') >= sharedConfig.minForCheckIn
                        local label = doctorsAvailable and 'text.call_doc' or 'text.check_in'
                        lib.showTextUI(locale(label))
                    end,
```
Not sure if we want to leave that check here or if we need the server to return a number via that function

2024-02-09 08:05 UTC, solareon commented on client/hospital.lua
> +                    end,
```suggestion
                    inside = function()
                        OnKeyPress(function()
                            checkIn(hospitalName)
                        end)
                    end,
```
The teleport out of the zone will clear the showTextUI

2024-02-09 08:05 UTC, solareon commented on client/hospital.lua
> +                    end,
Should we use OnKeyPress here?

2024-02-09 16:21 UTC, MafewTM commented on client/job.lua
>          while checkVehicle do
both of those are going to be removed.

2024-02-09 16:39 UTC, solareon approved these changes

2024-02-11 23:46 UTC, BerkieBb approved these changes

2024-02-12 00:30 UTC, merged