refactor(hospital:server:RespawnAtHospital): extracted functions
Qbox-project/qb-ambulancejob pull request #13
Opened 2022-12-19 07:27 UTC by Manason

**Describe Pull request**
- Extracted functions from server event 'hospital:server:RespawnAtHospital' to break up this large event function and reduce duplicate code.
- Minor improvements such as changing variable names. Otherwise no structural changes to extracted code

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-12-21 19:27 UTC, BerkieBb requested changes

2022-12-21 19:27 UTC, BerkieBb commented on server/main.lua
> +	MySQL.Async.execute('UPDATE players SET inventory = ? WHERE citizenid = ?', { json.encode({}), player.PlayerData.citizenid })
Change these to the new syntax (MySQL.update)

2022-12-21 20:04 UTC, BerkieBb approved these changes

2022-12-24 11:51 UTC, YvanCywan approved these changes

2022-12-24 16:58 UTC, merged