refactor(client/dead): setting downed states
Qbox-project/qb-ambulancejob pull request #16
Opened 2022-12-19 17:37 UTC by Manason

**Describe Pull request**
- extracted functions from thread which handles last stand and dead states
- replaced loadAnimDict local function with calls to ox_lib
- moved thread and dependent local functions to new file

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [no] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-12-21 10:29 UTC, BerkieBb requested changes

2022-12-21 10:29 UTC, BerkieBb commented on client/dead.lua
> +emsNotified = false
Why is this at the bottom?

2022-12-21 10:29 UTC, BerkieBb commented on client/setdownedstate.lua
> +local function drawTxt(x, y, width, height, scale, text, r, g, b, a, _)
The last underscore is useless, you can remove it

2022-12-21 10:29 UTC, BerkieBb commented on client/setdownedstate.lua
> +end
This won't actually return in the isEmsOnDuty function, but rather just end the execution of the callback, so this is the fix
```suggestion
local function isEmsOnDuty()
    local p = promise.new()
    QBCore.Functions.TriggerCallback('hospital:GetDoctors', function(medics)
        p:resolve(medics > 0)
    end)

    return Citizen.Await(p)
end
```

2022-12-21 10:29 UTC, BerkieBb commented on client/setdownedstate.lua
> +
weird empty space

2022-12-21 10:29 UTC, BerkieBb commented on client/setdownedstate.lua
> +    if IsPedInAnyVehicle(ped, false) then
replace with cache.vehicle

2022-12-21 10:29 UTC, BerkieBb commented on client/setdownedstate.lua
> +    if IsPedInAnyVehicle(ped, false) then
replace with cache.vehicle

2022-12-21 10:29 UTC, BerkieBb commented on client/setdownedstate.lua
> +    if IsPedInAnyVehicle(ped, false) then
replace with cache.vehicle

2022-12-21 10:29 UTC, BerkieBb commented on client/setdownedstate.lua
> +            Wait(5)
0 not 5

2022-12-21 10:29 UTC, BerkieBb commented on client/setdownedstate.lua
> +    local ped = PlayerPedId()
use cache.ped instead of the ped variable overall because this won't work anymore if the ped changes

2022-12-21 16:34 UTC, Manason commented on client/dead.lua
> +emsNotified = false
moved to the top.

2022-12-21 19:42 UTC, BerkieBb approved these changes

2022-12-24 11:28 UTC, YvanCywan approved these changes

2022-12-24 16:58 UTC, merged