refactor(client/wounding): general cleanup
Qbox-project/qb-ambulancejob pull request #17
Opened 2022-12-20 16:28 UTC by Manason

**Describe Pull request**
- extracted functions
- introduced guard clauses
- simplified expressions

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [no] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-12-21 10:33 UTC, BerkieBb requested changes

2022-12-21 10:33 UTC, BerkieBb commented on client/wounding.lua
> +        if (moving > 1 and not IsPedInAnyVehicle(player)) and isBleeding > 2 then
use cache.vehicle

2022-12-21 10:33 UTC, BerkieBb commented on client/wounding.lua
> +        local moving = #(vector2(prevPos.x, prevPos.y) - vector2(currPos.x, currPos.y))
```suggestion
        local moving = #(prevPos.xy - currPos.xy)
```

2022-12-21 10:33 UTC, BerkieBb commented on client/wounding.lua
> +    local player = PlayerPedId()
Use cache.ped

2022-12-21 10:33 UTC, BerkieBb commented on client/wounding.lua
> +    prevPos = GetEntityCoords(PlayerPedId(), true)
Use cache.ped

2022-12-21 10:33 UTC, BerkieBb commented on client/main.lua
> +bleedTickTimer, advancedBleedTimer = 0, 0
This was actually meant to be `advance` because once it's over it advances

2022-12-21 15:55 UTC, Manason commented on client/wounding.lua
> +        if (moving > 1 and not IsPedInAnyVehicle(player)) and isBleeding > 2 then
done

2022-12-21 19:48 UTC, BerkieBb approved these changes

2022-12-24 11:39 UTC, YvanCywan approved these changes
LGTM

2022-12-24 11:39 UTC, YvanCywan commented on client/wounding.lua
> +    end
```suggestion
    if painkillerAmount > 0 then return end
    painkillerAmount = 0
    onPainKillers = false
```

2022-12-24 17:04 UTC, merged