refactor: item callback for removal
Qbox-project/qb-ambulancejob pull request #37
Opened 2023-01-18 08:26 UTC by Manason

**Describe Pull request**
- simplified item removal events by using callbacks

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [no] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2023-01-19 21:19 UTC, BerkieBb requested changes

2023-01-19 21:19 UTC, BerkieBb commented on server/main.lua
> +	lib.callback(event, src, function(removeItem)
Use .await to reduce indentation

2023-01-19 21:19 UTC, BerkieBb commented on server/main.lua
> +		if removeItem then
Invert if statement

2023-01-19 21:30 UTC, Molicheu approved these changes

2023-01-20 10:29 UTC, BerkieBb approved these changes

2023-01-21 18:04 UTC, merged